### ISSUE TITLE
Server spans incorrectly marked as errors for client faults

### ISSUE THREAD

**Issue by nichtverstehen** [connectrpc/otelconnect-go#157] opened 2023-12-06 22:27 UTC
Per Otel spec for gRPC only errors indicating server fault (like `INTERNAL`) must result in the span being marked as errors.
https://opentelemetry.io/docs/specs/semconv/rpc/grpc/#grpc-status

Errors indicating a client fault (like `INVALID_ARGUMENT`) must not result in spans being marked as errors. This makes sense: for instance, user errors should not trigger alerts.

Otelconnect incorrectly reports all failed RPCs as errors here:
https://github.com/connectrpc/otelconnect-go/blob/main/interceptor.go#L357-L368

**Comment by jhump** [comment] 2023-12-07 13:24
@nichtverstehen, thanks for this report. We will look into a fix.

**Comment by jhump** [comment] 2023-12-08 20:16
This is actually a duplicate of #122. There was a proposed fix in #144. We originally had some concerns about accepting that change, but we're now revisiting and think that is indeed the right way to proceed.

Since it's a duplicate, I'm closing it, Please follow the other issue for updates.

**Closed by jhump** 2023-12-08 20:16 UTC
